spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:rate_limiter_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false #for high performance
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379
      timeout: 200ms
      lettuce:
        pool:
          max-active: 200
          max-idle: 100
          min-idle: 20
          max-wait: 100ms

# Moved OUT of the spring block
rate:
  limiter:
    mode: redis   # Now matches @ConditionalOnProperty(name = "rate.limiter.mode")

# Moved OUT of the spring block
resilience4j:
  circuitbreaker:
    instances:
      redisRateLimiter:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 60s
        sliding-window-size: 10
        minimum-number-of-calls: 5

server:
  tomcat:
    threads:
      max: 500
      min-spare: 50
    accept-count: 200